### PR TITLE
added url shortner in community examples

### PR DESCRIPTION
**Pull request by vinyashegde**
hope you like it :)

### CODE REVIEW

**Comment by vinyashegde** [comment]
@FeodorFitsner Hey can anyone please merge this pr?

**Comment by FeodorFitsner** [comment]
Is it ready for merge?

**Comment by vinyashegde** [comment]
> Is it ready for merge?

Yah it is

**Comment by vinyashegde** [comment]
Thanks I waited for months for this 😂 @FeodorFitsner

**Pull request merged**
